---
- name: Download SaltStack
  get_url:
    url: https://bootstrap.saltstack.com
    dest: /tmp/bootstrap-salt.sh

- name: Install SaltStack 
  shell: "sh /tmp/bootstrap-salt.sh -P {{ salt_version }}"

- name: Remove minion id.
  file:
    path: /etc/salt/minion_id
    state: absent

- name: Add salt IP to hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ salt_ip }} salt"
    state: present

- name: Stop salt-minion
  service:
    name: salt-minion
    state: stopped
    enabled: "{{ salt_enabled }}"
