---
# tasks file for salt
- name: Download SaltStack.
  shell: curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com

- name: Install SaltStack 
  shell: "sh bootstrap-salt.sh git {{ salt_version }}"

- name: Remove minion id.
  file:
    path: /etc/salt/minion_id
    state: absent

- name: Add salt IP to hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ salt_ip }} salt"
    state: present

- name: Stop salt-minion
  service:
    name: salt-minion
    state: stopped
    enabled: "{{ salt_enabled }}"
